server:
  port: 3000
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carsale
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  graphql:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.carsale.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长

jwt:
  token:
    tokenExpiration: 100
    tokenSignKey: carsale123

#  inventory
#  id  productId  warehouseId  quantity
#  order
#  id  userId  productId  warehouseId  createtime
#  product
#  id  name  model  price
#  supplier
#  id  name  phone
#  supply
#  id  productId  warehouseId  supplierId  quantity
#  user
#  id  username  phone
#  warehouse
#  id  location